# action.yml
name: 'Spring Application Advisor'
description: 'Incrementally upgrade your Spring application dependencies'
branding:
  icon: user-check
  color: green

inputs:
  artifactory_token:
    description: 'Token for Spring Enterprise Subscription'
    required: true

  git_token:
    description: 'Authentication token for generating pull requests against repo'
    required: true

  advisor_version:
    description: 'Spring Application Advisor CLI version'
    required: false
    default: '1.5.4'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: '21'
    - name: Cache advisor CLI
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/advisor
        key: advisor-cli-1.5.4

    - name: Download and install
      shell: bash
      run: |
        VERSION=1.5.4
        curl -L \
          -H "Authorization: Bearer $ARTIFACTORY_TOKEN" \
          -o /tmp/advisor-cli.tar \
          https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/$VERSION/application-advisor-cli-linux-$VERSION.tar
        tar -xf /tmp/advisor-cli.tar --strip-components=1 -C /tmp
        install /tmp/advisor /usr/local/bin/advisor
      env:
        ARTIFACTORY_TOKEN: ${{ inputs.artifactory_token }}
        
    - name: Run Spring Application Advisor
      run: ${{ github.action_path }}/app-advisor.sh
      shell: bash
      env:
        ARTIFACTORY_TOKEN: ${{ inputs.artifactory_token }}
        GIT_TOKEN_FOR_PRS: ${{ inputs.git_token }}
        ADVISOR_VERSION: ${{ inputs.advisor_version }}
