VERSION=1.5.4
# Install Cloud Foundry CLI
echo "Installing Cloud Foundry CLI..."
curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" -o /tmp/cf.tgz
tar -xzf /tmp/cf.tgz -C /tmp
sudo mv /tmp/cf /usr/local/bin/cf
chmod +x /usr/local/bin/cf
cf --version

curl -L -H "Authorization: Bearer $ARTIFACTORY_TOKEN" -o /tmp/advisor-cli.tar -X GET https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/$VERSION/application-advisor-cli-linux-$VERSION.tar
tar -xf /tmp/advisor-cli.tar --strip-components=1 -C /tmp
install /tmp/advisor /usr/local/bin/advisor
mkdir -p /home/runner/.m2
cat > /home/runner/.m2/settings.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>spring-enterprise-subscription</id>
      <username>eknath.reddy@broadcom.com</username>
      <password>${ARTIFACTORY_TOKEN}</password>
    </server>
  </servers>
  <profiles>
    <profile>
      <id>spring-enterprise</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>spring-enterprise-subscription</id>
          <url>https://packages.broadcom.com/artifactory/spring-enterprise</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>spring-enterprise-subscription</id>
          <url>https://packages.broadcom.com/artifactory/spring-enterprise</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>

  <activeProfiles>
    <activeProfile>spring-enterprise</activeProfile>
  </activeProfiles>

</settings>
EOF

advisor build-config get
#advisor build-config publish
advisor upgrade-plan get

advisor upgrade-plan apply

# Check if there are any changes to commit
if [[ -n $(git status --porcelain) ]]; then
  echo "Changes detected, creating branch and committing..."
  
  # Configure git
  git config --global user.name "Spring App Advisor Bot"
  git config --global user.email "spring-advisor-bot@broadcom.com"
  
  # Create a new branch with timestamp
  BRANCH_NAME="spring-advisor-upgrade-$(date +%Y%m%d-%H%M%S)"
  git checkout -b "$BRANCH_NAME"
  
  # Add all changes
  git add .
  
  # Commit with descriptive message
  git commit -m "Spring Application Advisor: Upgrade Java 8 to 11

Applied by Spring Application Advisor v1.5.4
  
Changes:
- Updated Java version from 8 to 11
- Updated Maven/Gradle configuration
- Applied necessary code transformations

Auto-generated commit by GitHub Actions"
  
  # Push the branch
  git push origin "$BRANCH_NAME"
  
  # Create a Pull Request (optional)
  export GH_TOKEN="${GH_TOKEN}"
  export GH_TOKEN="${GH_TOKEN:-$GITHUB_TOKEN}"

  gh pr create --title "Spring Upgrade using SAA" --body "Automated Spring upgrade generated by Spring Application Advisor v1.5.4" --head "$BRANCH_NAME" --base main
    
  echo "Created branch: $BRANCH_NAME"
  echo "Pushed changes to origin"
  echo "Created pull request"
else
  echo "No changes to commit"
fi


git branch -M "$BRANCH_NAME"

## Deploy the app into TP using CF push 
#cf api "$CF_API"
#cf auth "$CF_USERNAME" "$CF_PASSWORD"
#cf target -o "$CF_ORG" -s "$CF_SPACE"

#cf push

## Add to the repository in Hub 

#export TANZU_PLATFORM_URL="$TANZU_PLATFORM_URL"
#export TANZU_PLATFORM_OAUTH_APP_ID="$TANZU_PLATFORM_OAUTH_APP_ID"
#export TANZU_PLATFORM_OAUTH_APP_SECRET="$TANZU_PLATFORM_OAUTH_APP_SECRET"
#export TANZU_PLATFORM_API_ID="$TANZU_PLATFORM_API_ID"
#export TANZU_PLATFORM_ORG_ID="$TANZU_PLATFORM_ORG_ID"

#advisor build-config publish -d
