VERSION=1.5.4
curl -L -H "Authorization: Bearer $ARTIFACTORY_TOKEN" -o /tmp/advisor-cli.tar -X GET https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/$VERSION/application-advisor-cli-linux-$VERSION.tar
tar -xf /tmp/advisor-cli.tar --strip-components=1 -C /tmp
install /tmp/advisor /usr/local/bin/advisor

cat > /home/runner/.m2/settings.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>spring-enterprise-subscription</id>
      <username>eknath.reddy@broadcom.com</username>
      <password>${ARTIFACTORY_TOKEN}</password>
    </server>
  </servers>
  <profiles>
    <profile>
      <id>spring-enterprise</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>spring-enterprise-subscription</id>
          <url>https://packages.broadcom.com/artifactory/spring-enterprise</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>spring-enterprise-subscription</id>
          <url>https://packages.broadcom.com/artifactory/spring-enterprise</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>

  <activeProfiles>
    <activeProfile>spring-enterprise</activeProfile>
  </activeProfiles>

</settings>
EOF

advisor build-config get
advisor build-config publish
advisor upgrade-plan get

advisor upgrade-plan apply

# Check if there are any changes to commit
if [[ -n $(git status --porcelain) ]]; then
  echo "Changes detected, creating branch and committing..."
  
  # Configure git
  git config --global user.name "Spring App Advisor Bot"
  git config --global user.email "spring-advisor-bot@broadcom.com"
  
  # Create a new branch with timestamp
  BRANCH_NAME="spring-advisor-upgrade-$(date +%Y%m%d-%H%M%S)"
  git checkout -b "$BRANCH_NAME"
  
  # Add all changes
  git add .
  
  # Commit with descriptive message
  git commit -m "Spring Application Advisor: Upgrade Java 8 to 11

Applied by Spring Application Advisor v1.5.4
  
Changes:
- Updated Java version from 8 to 11
- Updated Maven/Gradle configuration
- Applied necessary code transformations

Auto-generated commit by GitHub Actions"
  
  # Push the branch
  git push origin "$BRANCH_NAME"
  
  # Create a Pull Request (optional)
  export GH_TOKEN="${GH_TOKEN}"
  export GH_TOKEN="${GH_TOKEN:-$GITHUB_TOKEN}"
  echo "GH_TOKEN length: ${#GH_TOKEN}"
  gh auth status

  gh pr create --title "Spring Upgrade using SAA" --body "Automated Spring upgrade generated by Spring Application Advisor v1.5.4" --head "$BRANCH_NAME" --base main
    
  echo "Created branch: $BRANCH_NAME"
  echo "Pushed changes to origin"
  echo "Created pull request"
else
  echo "No changes to commit"
fi


git branch -M "$BRANCH_NAME"

export TANZU_PLATFORM_URL=https://tanzuhub.app.eknathenv.tanzupartnerdemo.com
export TANZU_PLATFORM_OAUTH_APP_ID=1aFIzmvPd4iK11P8y05Ol0MecD1VNid
export TANZU_PLATFORM_OAUTH_APP_SECRET=e5mX2eMxLp8d6RGGzqST0s26Ovs7ooEKtHOhiJAANNvarg
export TANZU_PLATFORM_API_ID=ff76209e-da6d-4341-9db9-ae531b59d4a8
export TANZU_PLATFORM_ORG_ID=ecdff0a6-8e68-4d43-8f90-9ac02a265082

echo $TANZU_PLATFORM_URL
echo $TANZU_PLATFORM_OAUTH_APP_ID
echo $TANZU_PLATFORM_API_ID
echo $TANZU_PLATFORM_ORG_ID

echo $JAVA_HOME

advisor build-config get
advisor build-config publish
