VERSION=1.4.1
curl -L -H "Authorization: Bearer $ARTIFACTORY_TOKEN" -o /tmp/advisor-cli.tar -X GET https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/$VERSION/application-advisor-cli-linux-$VERSION.tar
tar -xf /tmp/advisor-cli.tar --strip-components=1 -C /tmp
install /tmp/advisor /usr/local/bin/advisor

cat > /home/runner/.m2/settings.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>spring-enterprise-subscription</id>
      <username>eknath.reddy@broadcom.com</username>
      <password>${ARTIFACTORY_TOKEN}</password>
    </server>
  </servers>
  <profiles>
    <profile>
      <id>spring-enterprise</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>spring-enterprise-subscription</id>
          <url>https://packages.broadcom.com/artifactory/spring-enterprise</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>spring-enterprise-subscription</id>
          <url>https://packages.broadcom.com/artifactory/spring-enterprise</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>

  <activeProfiles>
    <activeProfile>spring-enterprise</activeProfile>
  </activeProfiles>

</settings>
EOF

advisor build-config get

advisor build-config publish
advisor upgrade-plan get

advisor upgrade-plan apply

# Check if there are any changes to commit
if [[ -n $(git status --porcelain) ]]; then
  echo "Changes detected, creating branch and committing..."
  
  # Configure git
  git config --global user.name "Spring App Advisor Bot"
  git config --global user.email "spring-advisor-bot@broadcom.com"
  
  # Create a new branch with timestamp
  BRANCH_NAME="spring-advisor-upgrade-$(date +%Y%m%d-%H%M%S)"
  git checkout -b "$BRANCH_NAME"
  
  # Add all changes
  git add .
  
  # Commit with descriptive message
  git commit -m "Spring Application Advisor: Upgrade Java 8 to 11

Applied by Spring Application Advisor v1.3.1
  
Changes:
- Updated Java version from 8 to 11
- Updated Maven/Gradle configuration
- Applied necessary code transformations

Auto-generated commit by GitHub Actions"
  
  # Push the branch
  git push origin "$BRANCH_NAME"
  
  # Create a Pull Request (optional)
  # You can use GitHub CLI if available, or the GitHub API
  gh pr create \
    --title "Spring Upgrade: Java 8 to 11" \
    --body "This PR contains automatic upgrades applied by Spring Application Advisor.

**Changes Applied:**
- Java version upgraded from 8 to 11
- Build configuration updated
- Code transformations applied where necessary

**Next Steps:**
1. Review the changes carefully
2. Test the application
3. Merge if everything looks good

Generated by Spring Application Advisor v1.3.1" \
    --head "$BRANCH_NAME" \
    --base main
    
  echo "Created branch: $BRANCH_NAME"
  echo "Pushed changes to origin"
  echo "Created pull request"
else
  echo "No changes to commit"
fi
