name: Spring Application Advisor

on:
  # Run weekly on Monday at 9 AM
  schedule:
    - cron: '0 9 * * 1'
  
  # Allow manual triggers
  workflow_dispatch:
    inputs:
      create_pr:
        description: 'Create Pull Request'
        required: false
        default: 'true'
        type: boolean
      source_path:
        description: 'Source code path'
        required: false
        default: '.'
        type: string
  
  # Run on changes to build files
  push:
    branches:
      - main
    paths:
      - 'pom.xml'
      - 'build.gradle'
      - 'build.gradle.kts'
      - '**/pom.xml'
      - '**/build.gradle'
      - '**/build.gradle.kts'

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Spring Application Advisor
        id: advisor
        uses: eknathreddy09/spring-appadvisor-action@v1.4.0
        with:
          artifactory_token: ${{ secrets.ARTIFACTORY_TOKEN }}
          git_token: ${{ secrets.GITHUB_TOKEN }}
          source_path: ${{ github.event.inputs.source_path || '.' }}
          create_pr: ${{ github.event.inputs.create_pr || 'true' }}
          pr_title: "🔄 Spring Application Advisor: Dependency Upgrades"
          pr_body: |
            ## Spring Application Advisor Upgrade (Local Mode)
            
            This PR contains automated dependency upgrades suggested by Spring Application Advisor.
            
            ### What's Changed
            - Updated Spring Boot version
            - Updated Spring dependencies
            - Applied security patches
            - Updated build tool versions
            
            ### Testing
            Please review the changes and run your test suite before merging.
            
            ### Generated by
            - Action: Spring Application Advisor (Local Mode)
            - Triggered by: ${{ github.event_name }}
            - Date: ${{ github.run_id }}
          
      - name: Summary
        if: always()
        run: |
          echo "## Spring Application Advisor Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ steps.advisor.outputs.upgrade_status }}" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.advisor.outputs.upgrade_status }}" = "changes_applied" ]; then
            echo "- **Result**: ✅ Upgrades applied successfully" >> $GITHUB_STEP_SUMMARY
            if [ "${{ steps.advisor.outputs.pr_number }}" != "" ]; then
              echo "- **Pull Request**: [#${{ steps.advisor.outputs.pr_number }}](https://github.com/${{ github.repository }}/pull/${{ steps.advisor.outputs.pr_number }})" >> $GITHUB_STEP_SUMMARY
            fi
          elif [ "${{ steps.advisor.outputs.upgrade_status }}" = "no_changes" ]; then
            echo "- **Result**: ℹ️ No upgrades needed - your dependencies are up to date!" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Result**: ❌ Action completed with status: ${{ steps.advisor.outputs.upgrade_status }}" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.advisor.outputs.upgrade_status }}" = "changes_applied" ]; then
            echo "1. Review the pull request" >> $GITHUB_STEP_SUMMARY
            echo "2. Run your test suite" >> $GITHUB_STEP_SUMMARY
            echo "3. Merge when ready" >> $GITHUB_STEP_SUMMARY
          else
            echo "1. No action required" >> $GITHUB_STEP_SUMMARY
            echo "2. Monitor for future updates" >> $GITHUB_STEP_SUMMARY
          fi
